baseurl: /news
exclude: [tools,update_mantid_git.sh]
permalink: /:year/:month/:title.html
projecthome: http://www.mantidproject.org
downloadpage: http://download.mantidproject.org/
pygments: true
safe: true
markdown: kramdown
