baseurl:
exclude: [README.md,tools,update_mantid_git.sh]
permalink: /:year/:month/:title.html
projecthome: http://www.mantidproject.org
downloadpage: http://download.mantidproject.org/
docpage: http://docs.mantidproject.org/
safe: true
markdown: kramdown
