baseurl: /news
exclude: [tools]
permalink: /:year/:month/:title.html
projecthome: http://www.mantidproject.org
downloadpage: http://download.mantidproject.org/
pygments: true
safe: true
markdown: kramdown
