baseurl:
exclude: [README.md,tools,update_mantid_git.sh]
permalink: /:year/:month/:title.html
projecthome: http://www.mantidproject.org
downloadpage: http://download.mantidproject.org/
docpage: http://docs.mantidproject.org/
mantidrepo: https://www.github.com/mantidproject/mantid
mantidbuilds: http://builds.mantidproject.org/
mantidreleasebuilds: http://builds.mantidproject.org/view/Release%20Pipeline/
safe: true
markdown: kramdown
